version: 0.2
          
phases:
  install:
    runtime-versions:
      java: 1.8
    commands:
      - echo install
  pre_build:
    commands:
      - echo pre_build
  build:
    commands:
      - mvn package
      - echo build
  post_build:
    commands:
      - echo post_build

artifacts:
  files:
      - target/spring-boot-security-jwt-0.0.1-SNAPSHOT.jar